### ISSUE TITLE
Inconsistent behaviour when jumping in and out of YT app using restore icon on video window

### ISSUE THREAD

**Issue by DragRedSim** [PoomSmart/YouPiP#6]
Activate PIP, home out, return to app using icon, home out again: works (same applies for using app switcher)
Activate PIP, home out, return to app using video restore icon, home out again: does not work, video continues to play audio but not display the video. To fix, need to return to YT app and then leave again.

**Comment by PoomSmart** [comment]
Fixed in 1.2.1, although YouPiP's behavior is explicitly mentioned in its Settings page. This issue could have otherwise been invalid.

**Comment by DragRedSim** [comment]
v1.2.1 does not resolve this issue; I have it on “app dismiss” mode. A demonstration: https://youtu.be/O_DSl0OntqE
Sorry, I should have been clearer; the issue is when restoring the PiP video using the button in that view (as opposed to app switcher or app icon), then dismissing the YT app again.

**Comment by PoomSmart** [comment]
@DragRedSim How about version 1.3.0?
